[project]
name = "gdacs-flood-db"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "geopandas>=1.1.2",
    "numpy>=2.4.0",
    "pandas>=2.3.3",
]
